### ISSUE TITLE
Banner - titulos e categorias

### ISSUE THREAD

**Issue by ccspgithub** [marcioyonamine/karta-ccsp#15]
![image](https://cloud.githubusercontent.com/assets/28657233/26009552/b201d6f4-371f-11e7-9dfc-5b9d72b15d9d.png)

- Título em preto com mesma tipografia dos demais títulos. 
Deixar em duas ou três linhas títulos muito grandes 
- Box de categoria colado ao titulo, 
- Posição fixa no canto inferior direito padrão para todos
- Rever as transições* 
*me avisaram que o Edimas está mexendo nisso, assim que testar posso ajudar na escolha de um!

**Comment by marcioyonamine** [comment]
O banner não é automatizado. Vai no config do plugin.
