### ISSUE TITLE
Titulos vermelhos do rodapé

### ISSUE THREAD

**Issue by ccspgithub** [marcioyonamine/karta-ccsp#17]
![image](https://cloud.githubusercontent.com/assets/28657233/26009897/26fa9c56-3721-11e7-842e-a00847cd8d7a.png)
- Como todos os links estão vermelhos agora, acho mais viável deixar esses títulos (como o selecionado no print) pretos para destacar dos links

**Comment by marcioyonamine** [comment]
falei que era meio estranho todos os links em vermelho.

**Comment by ccspgithub** [comment]
Ahh, mas tranquilo!! ou força esses a serem pretos ou os titulos pretos! só pra não acharem que tudo é link! ;)
