### ISSUE TITLE
CCSP'

### ISSUE THREAD

**Issue by ccspgithub** [marcioyonamine/karta-ccsp#31]
![image](https://cloud.githubusercontent.com/assets/28657233/26017097/52a2805e-373e-11e7-9ea9-999157b0667f.png)
![image](https://cloud.githubusercontent.com/assets/28657233/26017293/39863ac4-373f-11e7-95bf-90309fac6bf9.png)

- Página ainda encontra-se com imagem em background semelhante as paginas de evento. Padronizar página como as de biblioteca e acervo, todas essas, com imagens pb em 50% de opacidade

**Comment by marcioyonamine** [comment]
É só tirar a imagem em destaque.

**Comment by ccspgithub** [comment]
Então Márcio, lembra que nessa página a ideia era ser igual a de biblioteca. A gente tinha conversado de criar uma série de páginas de fotos institucionais em background, essa página é uma delas. Se eu tirar a foto, como ela vai entrar no background? Não é no código?

**Comment by marcioyonamine** [comment]
Sim. Tira a imagem em destaque e coloca o endereço no campo custom css URL da Imagem que ela vai para o background
